### ISSUE TITLE
 How to play songs with a "streaming" status, similar to how it happens on Suno?

### ISSUE THREAD

**Issue by ablaevrs** [gcui-art/suno-api#105]
Hello everyone. I'm receiving a response from Suno with a link to an audio file with the status "streaming". On Suno, I can already start listening to the song at this time. However, on my own service, I cannot play the song. I have to wait until the status changes to "completed". But this process takes quite a lot of time. Do you have a solution for playing audio files with the "streaming" status?

**Comment by blueeon** [comment]
Suno’s generation is asynchronous, you need to create a task using the generate API, and then use the get API to loop through the status. 
And recently, I found that sometimes it hangs, seems to be an issue with SUNO’s own service. Hope this helps you.

**Comment by rustem-git** [comment]
I figured it out. The problem was that Suno replaces the link. Initially, the link comes with an ID for streaming, but when the song is ready, the field gets the mp3 link. I implemented the check, and everything started working. Thank you for your response.

**Comment by ablaevrs** [comment]
> Suno’s generation is asynchronous, you need to create a task using the generate API, and then use the get API to loop through the status. And recently, I found that sometimes it hangs, seems to be an issue with SUNO’s own service. Hope this helps you.

I figured it out. The problem was that Suno replaces the link. Initially, the link comes with an ID for streaming, but when the song is ready, the field gets the mp3 link. I implemented the check, and everything started working. 

Thank you for your response
