### ISSUE TITLE
大佬，有空的时候,能否考虑兼容一下oneapi或者newapi和Docker-Compose部署？

### ISSUE THREAD

**Issue by dcln78** [gcui-art/suno-api#12]
大佬，有空的时候,能否考虑兼容一下oneapi或者newapi？

**Comment by blueeon** [comment]
Could you please provide some information about how you intend to use it and where it will be used? 
This will help us better grasp your issue.

**Comment by blueeon** [comment]
https://github.com/gcui-art/suno-api/issues/15
https://github.com/gcui-art/suno-api/issues/3
