### ISSUE TITLE
Add "Continue API" for songs in Suno AI API

### ISSUE THREAD

**Issue by VladimirKoh** [gcui-art/suno-api#13]
Hello,

We are working on implementing your Suno AI API into one of the largest neural bots in Telegram, but we have just found that there is no option to "Continue" the song. Is it possible for you to implement this feature? If it's a paid service, we can pay you for this work.

Look forward to hearing from you soon. 

Best Regards, 
Vladimir

**Comment by blueeon** [comment]
We’ll make it happen.

**Comment by blueeon** [comment]
@VladimirKoh At the moment, we are not looking to accept donations. Your support for this project through promotion, raising issues, and submitting pull requests is what truly motivates us!

**Comment by wizeddev** [comment]
> We’ll make it happen.

Hey - I just wanted to check if this is already available, I would love to pay for it, just take my money ;-)

**Comment by blueeon** [comment]
@VladimirKoh @wizeddev  A PR has been submitted, implementing this API #50 , and  waiting for another teammate to merge it.
Also, thanks for the pep talk, haha~
