### ISSUE TITLE
Support Suno's new feature: Exclude Styles

### ISSUE THREAD

**Issue by csiejoey** [gcui-art/suno-api#158]
**Is your feature request related to a problem? Please describe.**
new suno feature on 9/19 Exclude Styles

**Describe the solution you'd like**
Tried on the web ui, seems like simply adding a 'negative_tags' in the payload
![Screen Shot 2024-09-20 at 16 38 13](https://github.com/user-attachments/assets/9587b9a2-1748-4c8f-b04c-72f4c84d393e)
![image](https://github.com/user-attachments/assets/598d89b7-8ce6-4d91-876b-dfc02d9792ef)

**Describe alternatives you've considered**

**Additional context**
Thank you very much, appreciate the hard work!

**Comment by sebpar** [comment]
I've tried this in the body of the request, but it didn't work:

{
  "prompt": "Ambient music",
  "make_instrumental": true,
  "wait_audio": false,
  "negative_tags": "piano"
}

Is this normal? Were you able to make it work?

**Comment by sebpar** [comment]
Hopefully, you can find a solution. I've tried but without success. Hopefully, a developer better than me can solve this.

**Comment by glitchbunny0** [comment]
Confirmed and implemented in [my fork](https://github.com/glitchbunny0/suno-api) (PR #286). `negative_tags` is accepted in the generate payload exactly as you described. Works in both `generate` and `custom_generate` modes, and also in extend/cover flows.
