### ISSUE TITLE
query ids= doesnt return the list i gave it

### ISSUE THREAD

**Issue by carinama1** [gcui-art/suno-api#187]
**Describe the bug**
I dont know if this is a bug or something changed to suno api, i feel like i am missing something, when i try to get api/get with no ids it works just fine, it returns every music in my account, but when i fetch it with ids 

`api/get/?ids=some_id_here`

 which fetch 

`https://studio-api.suno.ai/api/feed?ids=some_id_here`

it returns `404: data: { detail: 'Not found.' }` Im i missing something? or does this broken for everyone else as well?

**Expected behavior**
Returns musics ids detail

**Screenshots**
![image](https://github.com/user-attachments/assets/bf440d70-a9e5-4fd4-93ec-7b354f27aaf6)

**Comment by carinama1** [comment]
so are outside host not allowed to get a single music with id? im guessing, single clip are also returning Not Found

`/api/clip/b7891a33-fa18-4a68-b412-8d0fe1af28fe`

**Comment by uisato** [comment]
Hey, are the cookies working for you? Can't seem to make it work, having the "Internal server error. Error: Failed to get session id, you may need to update the SUNO_COOKIE".

**Comment by carinama1** [comment]
the cookies are working just fine for me
