### ISSUE TITLE
why

### ISSUE THREAD

**Issue by banxian007** [gcui-art/suno-api#19]
{
    "error": "Internal server error. TypeError [ERR_INVALID_CHAR]: Invalid character in header content [\"Cookie\"]"
}

![453736ebfe5fda143cdd841d3b54891](https://github.com/gcui-art/suno-api/assets/145275873/6617fc2b-8389-413a-b151-4f8a6162650d)
![af65db25facedcc8f8209632a059cbc](https://github.com/gcui-art/suno-api/assets/145275873/913b824f-0b3e-4aad-a43e-67dfa01e86da)
![image](https://github.com/gcui-art/suno-api/assets/145275873/7fcf6737-d22e-4041-88a4-bad2be603fd1)

**Comment by banxian007** [comment]
something wrong

**Comment by hiboydidi** [comment]
me too,why

**Comment by GitPusher99** [comment]
Go to https://app.suno.ai/, make sure you are logged in, and perform the operation on the console

``` js
function getCookieStringByDomain(domain) {
    const cookies = document.cookie.split(';');
    let cookieString = '';
    
    cookies.forEach(cookie => {
        const [name, value] = cookie.trim().split('=');
        cookieString += `${name}=${value}; `;
    });
    
    return cookieString;
}

getCookieStringByDomain('clerk.suno.ai');
```
You can get the cookie. Give it a try

@banxian007 @hiboydidi

**Comment by banxian007** [comment]
Tried all three browsers, Google Chrome, Firefox, and edge.


![image](https://github.com/gcui-art/suno-api/assets/145275873/5e0c5201-d6b6-4873-bb62-9acdbbebe3ca)
![image](https://github.com/gcui-art/suno-api/assets/145275873/c2366b42-b4ce-480d-9e16-9959efd2e910)
![image](https://github.com/gcui-art/suno-api/assets/145275873/a8a14c9d-7b4d-4ea3-9691-878b4c0c318e)
![image](https://github.com/gcui-art/suno-api/assets/145275873/933373bd-b1fa-4d0b-adc2-70cb07ce5ccb)

**Comment by banxian007** [comment]
@GitPusher99

**Comment by GitPusher99** [comment]
Look at the screenshot you sent, posted cookies contain special characters, you check to try

**Comment by banxian007** [comment]
> Look at the screenshot you sent, posted cookies contain special characters, you check to try

What special characters, I don't quite understand, like this？%     I don't know what the problem is.@GitPusher99

**Comment by GitPusher99** [comment]
<img width="883" alt="image" src="https://github.com/gcui-art/suno-api/assets/165138458/fcb721b7-4736-4985-b2ef-033e383d190d">

@banxian007

**Comment by Thehappydeveloper** [comment]
Hi, I have the same issue both when I run it with npm and with docker. 
![image](https://github.com/gcui-art/suno-api/assets/64440813/d27ca0be-8c72-4f0e-a1a9-13d5df9c095e)

I got the cookie ID with the function given above.

![image](https://github.com/gcui-art/suno-api/assets/64440813/3c2f645d-c3ce-4700-b4b8-c4478a685a43)

I inserted it in the example file like this:

![image](https://github.com/gcui-art/suno-api/assets/64440813/724d5e49-b0b7-42be-a1e2-b4d0f517da96)

I am on a Ubuntu machine.

**Comment by zilton7** [comment]
which browser you're using to get the Cookie? I had the same issue using Firefox, but it worked on Chromium ;)
