### ISSUE TITLE
internal server error. AxiosError: Request failed with status code 401

### ISSUE THREAD

**Issue by Marcioghiraldelli** [gcui-art/suno-api#191]
Anyone else having this problem?
I've already created several logins, cookies, etc. and it doesn't work.

**Comment by gohoski** [comment]
Have you tried [this](https://github.com/gcui-art/suno-api/issues/164#issuecomment-2406433730)? Either way, the authorization algorithm has changed (need to generate a special session token) and I am working on a fix.
