### ISSUE TITLE
I get a 500 error, I opened and entered different free accounts. What do you suggest to fix this problem.

### ISSUE THREAD

**Issue by Ozgundogus** [gcui-art/suno-api#192]
**Describe the bug**

With Vercel, I was creating a private repo with different names and sending API requests with the URL here. I was doing these differently from free accounts, but now all accounts are giving 500 errors. No matter if I delete and recreate it or try it from another computer. What solutions can I do for this problem. If it will be fixed by buying a premium account from Suno AI, please tell me that too. 
PS: By the way, I have been able to send API requests for about 1 month without any problem. On November 16th this problem appeared

**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="1058" alt="Ekran Resmi 2024-11-16 19 42 05" src="https://github.com/user-attachments/assets/8179af16-16b2-4742-8c9f-008c27898ec5">

**Desktop (please complete the following information):**

**Additional context**

**Comment by gohoski** [comment]
I am currently working on a fix, don't worry =)

**Comment by Ozgundogus** [comment]
Is there a Linkedn, Twitter or e-mail where I can reach you? Or if I write to you, can we talk about this privately?

**Comment by gohoski** [comment]
> Is there a Linkedn, Twitter or e-mail where I can reach you? Or if I write to you, can we talk about this privately?

I have Telegram, Discord and an e-mail address, all linked in my GitHub

**Comment by Ozgundogus** [comment]
When will the PR be approved?  @gohoski

**Comment by jrouxel** [comment]
Same thing. It was working fine 3 days ago, but since Friday all i get are 500 errors
![Capture d’écran, le 2024-11-18 à 15 22 41](https://github.com/user-attachments/assets/a750ea46-7b84-4480-96c2-9337b9ca7d6e)

**Comment by marc101101** [comment]
if you have the same problem. Suno added hidden captchas and the PR will hopefully solve that => https://github.com/gcui-art/suno-api/pull/193

**Comment by gohoski** [comment]
I'm currently working on it and waiting your opinions about the (paid) solutions to this problem, see the PR that Markus linked below

**Comment by sontl** [comment]
i'm fine with paid solution

**Comment by itrcz** [comment]
> I'm currently working on it and waiting your opinions about the (paid) solutions to this problem, see the PR that Markus linked below

Yes please.

> i'm fine with paid solution

Totally agree - paid is fine.

**Comment by Alazka2k** [comment]
@gohoski after the fix with the solution, can you add additional information in the Readme? Up to now I was only a quiet reader (and user of the project). Looking forward to the fix. I would also go with solution 3. Thx for your effort

**Comment by abatrutdinaff** [comment]
I support the posts above, paid bypass is a great solution

**Comment by PBEmanuel** [comment]
I bought credits and it worked, so the paid account is working.

**Comment by samuel-cox** [comment]
So, just to confirm @PBEmanuel, you're saying the normal codebase on this GitHub works if you buy suno credits?

**Comment by PBEmanuel** [comment]
@samuel-cox yes! =)

**Comment by abatrutdinaff** [comment]
I have a paid account but still the error that incorrect token, how were you able to resolve it?
