### ISSUE TITLE
In Suno Songs comes "This is a Fake App use Suno"

### ISSUE THREAD

**Issue by Kev2012** [gcui-art/suno-api#194]
Hey have since today this Problem:

If I generate over your API the Song in My Song is to hear:

"This is a Fake App please Go to Suno ... "

Have any other People also this Problem? :/

**Comment by gohoski** [comment]
Wow, Suno now does even that…

We are trying to solve and discuss the issues that Suno is making with CAPTCHAs in this PR: #193

**Comment by marc101101** [comment]
yeah looks like they are shutting down the party ...

**Comment by TimBrunsmo** [comment]
I can confirm this. Also get the "This is a fake app"-songs now..

**Comment by johbs** [comment]
Me too. Today, V4 was released. We need to check again what the new conditions for API post/request are and if there have been any changes.

**Comment by omkardigikore** [comment]
Has anyone found a solution for this?

**Comment by anelder-human** [comment]
I've just hit the fake app problem - so frustrating as a subscriber that they simply don't seem to want custom.

**Comment by TimBrunsmo** [comment]
Public API is in their roadmap.
