### ISSUE TITLE
support v4 - new suno api repo

### ISSUE THREAD

**Issue by gochendong** [gcui-art/suno-api#197]
https://github.com/gochendong/suno-api 

support latest v4 model

**Comment by kevin-mindverse** [comment]
http://localhost:8000/docs is blank~~~~~

**Comment by sunosongai330** [comment]
https://github.com/gochendong/suno-api/issues/1 as that is mentioned there, it is not working.

**Comment by gochendong** [comment]
> http://localhost:8000/docs is blank~~~~~

it's impossible, unless it's not running
