### ISSUE TITLE
Internal server error. AxiosError: Request failed with status code 401

### ISSUE THREAD

**Issue by Vals0ray** [gcui-art/suno-api#203]
I deployed repo to vercel, added SUNO_COOKIE environment variable, but endpoints return the next error:
```
{
  "error": "Internal server error. AxiosError: Request failed with status code 401"
}
```
Error from vercel deployment log:
```
Error fetching limit: U [AxiosError]: Request failed with status code 401
    at eM (/var/task/.next/server/chunks/577.js:304:3640796)
    at IncomingMessage.<anonymous> (/var/task/.next/server/chunks/577.js:306:8492)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
    at is.request (/var/task/.next/server/chunks/577.js:306:16932)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async m.keepAlive (/var/task/.next/server/app/api/get_limit/route.js:1:4240)
    at async m.init (/var/task/.next/server/app/api/get_limit/route.js:1:3460)
    at async _ (/var/task/.next/server/app/api/get_limit/route.js:1:8659)
    at async c (/var/task/.next/server/app/api/get_limit/route.js:1:1860)
    at async /var/task/node_modules/.pnpm/next@14.1.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
    at async eI.execute (/var/task/node_modules/.pnpm/next@14.1.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
    at async eI.handle (/var/task/node_modules/.pnpm/next@14.1.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737)
    at async Y (/var/task/node_modules/.pnpm/next@14.1.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:24659) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function (anonymous)] ],
    transformResponse: [ [Function (anonymous)] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36',
      Cookie: '{my cookies here}',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    jar: E {
      rejectPublicSuffixes: true,
      enableLooseMode: false,
      allowSpecialUseDomain: true,
      store: { idx: [Object: null prototype] {
        'suno.com': [Object: null prototype] {
          '/': [Object: nu
```

I tried different SUNO_COOKIE options (removed cookies that are not in the video guide on the documentation page)

Here is the request where I took the cookies:
![image](https://github.com/user-attachments/assets/0fd85d01-a4cb-45cf-84a3-73b2a2de9ce0)

Here is how my cookies looks like:
```
_cfuvid={some text here};
__client={some text here}; 
__client_uat={some text here};
__client_uat_U9tcbTPE={some text here}; 
_ga={some text here}; 
ajs_anonymous_id={some text here}; 
mp_26ced217328f4737497bd6ba6641ca1c_mixpanel={some text here}; 
__cf_bm={some text here}; 
_ga_7B0KEDD7XP={some text here}
```

Does anyone have any ideas what I'm doing wrong?

**Comment by bhushanrathod32** [comment]
Please check pr #202 or issue #201

**Comment by Ozgundogus** [comment]
Can you generate songs with API ? I guess this problem has not been solved for a long time, right? @Vals0ray @bhushanrathod32

**Comment by bhushanrathod32** [comment]
You need to generate one song from website manually to validate hcaptcha, after that you can generate songs

**Comment by Vals0ray** [comment]
> Can you generate songs with API ? I guess this problem has not been solved for a long time, right? @Vals0ray @bhushanrathod32

I cant, /api/generate returns:
{
  "error": "Internal server error: undefined"
}
In vercel logs I see the next error:
Error generating custom audio: {"errors":[{"message":"CAPTCHA verification is required","long_message":"CAPTCHA verification is required","code":"requires_captcha"}],"clerk_trace_id":"383f42329da864c8070d732612dcd0f5"}

> You need to generate one song from website manually to validate hcaptcha, after that you can generate songs

I have already generated a few, but the captcha verification was not requested on website

**Comment by bhushanrathod32** [comment]
private async getClerkLatestVersion() {
...
// Define the Clerk version as a constant or fetch it dynamically
const STABLE_CLERK_VERSION = "4.74.0";
this.clerkVersion = STABLE_CLERK_VERSION;
}

ensure it uses a Clerk version released prior to the implementation of fraud detection

**Comment by Vals0ray** [comment]
> private async getClerkLatestVersion() { ... // Define the Clerk version as a constant or fetch it dynamically const STABLE_CLERK_VERSION = "4.74.0"; this.clerkVersion = STABLE_CLERK_VERSION; }
> 
> ensure it uses a Clerk version released prior to the implementation of fraud detection

That works, thank you so much!

**Comment by zcwingo** [comment]
{"error":"Internal server error. AxiosError: Request failed with status code 401"}  please help me。Even if it's modified, it won't work

**Comment by zcwingo** [comment]
> Has the music generation problem been solved?

no~ and you?
