### ISSUE TITLE
Getting an error when running the test code

### ISSUE THREAD

**Issue by alxgt1000** [gcui-art/suno-api#25]
I write because I'm having trouble implementing it into my code. As context, I have the Suno pro version and https://<vercel-assigned-domain>/api/get_limit works well.

First I was getting an error in the return response.json() line ( error: "JSONDecodeError: Expecting value: line 1 column 1 (char 0)")

And now im getting this: https://drive.google.com/file/d/1R4EvkilCZ9Y8F0O6KV9uMiVUoxmW_tF1/view?usp=drivesdk

I would appreciate if you could let me know how to solve this issue, or if this is some kind of block from Suno (I don't think so as https://<vercel-assigned-domain>/api/get_limit is working but just checking)

**Comment by GitPusher99** [comment]
The interface should be fine

<img width="698" alt="image" src="https://github.com/gcui-art/suno-api/assets/165138458/df7cb787-f347-4160-a10e-b992a5260243">

Do we get any results from this test?
```
curl -X 'GET' \
  'http://{your host}/api/get_limit' \
  -H 'accept: application/json'
```
  @alxgt1000

**Comment by alxgt1000** [comment]
I get invalid syntax error

![image](https://github.com/gcui-art/suno-api/assets/164784957/83df3016-24bb-4370-b5f3-07d063d2acb3)

**Comment by alxgt1000** [comment]
But if I put it in chrome it works
![image](https://github.com/gcui-art/suno-api/assets/164784957/4c42352b-8a74-4535-a9a7-5e3699f18cf3)

**Comment by GitPusher99** [comment]
@alxgt1000 
curl -X 'GET' \
  'https://suno-api-cyan.vercel.app/api/get_limit' \
  -H 'accept: application/json'
  
This is my temporary test service, you try it, will there be such a problem?

**Comment by alxgt1000** [comment]
@GitPusher99 Thanks for the test, unfortunately I still get the same issue in the terminal "SyntaxError: invalid syntax"

![image](https://github.com/gcui-art/suno-api/assets/164784957/39303a00-2ae4-4619-b925-7e1a6f853f6a)

Any advice based on the image? It seems it doesn't recognize the variables/parameters

**Comment by GitPusher99** [comment]
Can you test it with postman? @alxgt1000

**Comment by alxgt1000** [comment]
Yes, It works here!

![image](https://github.com/gcui-art/suno-api/assets/164784957/902bf13c-c3de-4f32-94c2-5362e8302ead)

How could I integrate code like this to create songs for my saas apps?

**Comment by blueeon** [comment]
@alxgt1000 We will utilize it as a microservice to create music for our SaaS.
