### ISSUE TITLE
是否可以支持与openai兼容的 /v1/chat/completions 接口

### ISSUE THREAD

**Issue by kokojacket** [gcui-art/suno-api#3]
是否可以支持与openai兼容的 /v1/chat/completions 接口

**Comment by GitPusher99** [comment]
你是在什么使用场景？ @kokojacket

**Comment by kokojacket** [comment]
想要直接通过openai的接口接到类似于nextchat这种项目上。目前找了个第三方api接入。
![e47278a0b6b9ae7e6e9cc69954578d8](https://github.com/gcui-art/suno-api/assets/74887370/81008de2-3d3c-4847-9ca0-cb2049d2a285)

**Comment by dcln78** [comment]
> 想要直接通过openai的接口接到类似于nextchat这种项目上。目前找了个第三方api接入。 ![e47278a0b6b9ae7e6e9cc69954578d8](https://private-user-images.githubusercontent.com/74887370/318023398-81008de2-3d3c-4847-9ca0-cb2049d2a285.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTEzODAsIm5iZiI6MTcxMTk5MTA4MCwicGF0aCI6Ii83NDg4NzM3MC8zMTgwMjMzOTgtODEwMDhkZTItM2QzYy00ODQ3LTljYTAtY2IyMDQ5ZDJhMjg1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDE3MDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0OTVjOTk5YWRjZjNkM2IzNzU2NGRjNmNmYjU2ZGY0NDJmOGQzZDlhYmFmYmY4NzZkZmQ4Y2ZhZGExYmQwODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nH08X2AUilQZRe3NBZA7FCzX0a2ew7lp64uXE2tdg8c)

都有第三方接口了？能给个链接吗?

**Comment by yuanjie-ai** [comment]
> 想要直接通过openai的接口接到类似于nextchat这种项目上。目前找了个第三方api接入。 ![e47278a0b6b9ae7e6e9cc69954578d8](https://private-user-images.githubusercontent.com/74887370/318023398-81008de2-3d3c-4847-9ca0-cb2049d2a285.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMjk4MzIsIm5iZiI6MTcxMjEyOTUzMiwicGF0aCI6Ii83NDg4NzM3MC8zMTgwMjMzOTgtODEwMDhkZTItM2QzYy00ODQ3LTljYTAtY2IyMDQ5ZDJhMjg1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA3MzIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZTZhYjUxNWExODYzMjBlMjA1ZjZhNzQ2MTFkM2M0N2E3ZjY1Mzg3ZTA0MzAwM2FiMTg2MjE1Yjc1MjBjYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P0w3pohQSxdMTn7oWtUPNuNr9eXs6iMr_ZvuYMt3O10)

https://api.chatfire.cc可以接入

**Comment by GitPusher99** [comment]
<img width="417" alt="image" src="https://github.com/gcui-art/suno-api/assets/165138458/7f6c3a6d-7385-4a86-8ee1-8fdaaaf34f51">

已经支持，可以试试下
