### ISSUE TITLE
Failed to get session id

### ISSUE THREAD

**Issue by zion-c** [gcui-art/suno-api#30]
**Describe the bug**
After running stably for two days, today it started to report an error: Failed to get session id.

{"error":"Internal server error. Error: Failed to get session id, you may need to update the SUNO_COOKIE"}

**Comment by zion-c** [comment]
I found that the _clerk_js_version changed from 4.71.0 to 4.72.0.

**Comment by zion-c** [comment]
After updating the cookie, it's fine now.

**Comment by GitPusher99** [comment]
Yes, cookies need to be updated regularly  @zion-c
