### ISSUE TITLE
如果调用 suno API 控制其一次生成歌曲的数量？

### ISSUE THREAD

**Issue by Kevin-free** [gcui-art/suno-api#34]
当前调用 generate 默认是生成 2 首歌曲，请问可以控制生成的数量吗？以及消耗的 credits 是否有变化？

**Comment by Kevin-free** [comment]
> You can’t do this due to the limitations of the official Suno API. However, you can achieve this by making concurrent calls to the suno-api.

Thanks Reply. So I can do multiple operations (concurrently calling suno-api multiple times) on the basis of the smallest unit (generating two songs at a time). 
Is it possible to **generate one song at a time**?

**Comment by blueeon** [comment]
Sure thing.
The limitation doesn’t lie within suno-api. The generation process is asynchronous; when you call the generation API, it simply adds a task.

**Comment by blueeon** [comment]
> > Sure thing. The limitation doesn’t lie within suno-api. The generation process is asynchronous; when you call the generation API, it simply adds a task.
> 
> Thanks! I see that the request payload of suno API `/api/generate/v2/` does not have a parameter to control the minimum number of songs generated at a time, so at least two songs are generated at a time. I want to generate only one song at a time. 😂

That’s Suno’s design, we can’t mess with it.

**Comment by Kevin-free** [comment]
Thanks!
