### ISSUE TITLE
API works only on first run

### ISSUE THREAD

**Issue by Mousemaster12** [gcui-art/suno-api#38]
**Describe the bug**
When I start the api with npm run dev, it will only work once, even if i restart it 

**To Reproduce**
1. Clone Repo
2. Install Node.js (on arch use pacman)
3. run npm install and npm run dev
4. add cookie to .env
5. use the demo python code - first time should work
6. run the demo code again - hangs 

**Expected behavior**
It should have worked both times

**Screenshots**
![image](https://github.com/gcui-art/suno-api/assets/142980781/987dab8f-774d-4aa1-abb7-73c0995b0690)
it just continues with this until it stops, producing nothing 
**Desktop (please complete the following information):**
 - OS: Win11, also tried on Arch Linux
 - Browser: Firefox

**Comment by blueeon** [comment]
This is strange, I will test this issue today. Thank you for your feedback. @Mousemaster12

**Comment by blueeon** [comment]
There have been some changes to the official suno API, and I’ve updated it today. It’s now working fine in my local setup and on Vercel. Could you please test it out? Thanks a lot. #42

**Comment by Mousemaster12** [comment]
idk what was the issue, but it now works perfectly on my local arch Linux setup, haven't tested it on windows yet. thank you!

**Comment by vettorazi** [comment]
I'm having a similar issue. on my local environment is working fine. but the vercel says that I need to update the key (using the same key in both environments)

**Comment by blueeon** [comment]
@vettorazi  Have you updated the cookie key after deployment? Give it a try with the latest key?
