### ISSUE TITLE
使用docker-composer构建启动项目会将服务器卡死

### ISSUE THREAD

**Issue by y1713375484** [gcui-art/suno-api#39]
**Describe the bug**
<img width="1331" alt="image" src="https://github.com/gcui-art/suno-api/assets/80376536/ef0de1a0-3fa1-4dac-b61a-8bff5e0840d7">
使用两个服务器尝试都会在这里卡住，好奇怪，最离谱的是，阿里云强制关机都不行

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by blueeon** [comment]
Will we run into this issue when deploying locally? We haven’t come across this issue locally yet. Could you assist in reproducing and pinpointing the problem? Thank you. @y1713375484

**Comment by y1713375484** [comment]
> 在本地部署时会遇到这个问题吗？我们还没有在本地遇到这个问题。您能协助重现和查明问题吗？谢谢。

本地并未尝试，我这边怀疑是我的服务器内存太小了，两个都是双核1G内存的，以至于说，我不使用docker构建项目，安装了node跑这个项目偶尔写歌时都会将服务器卡住
