### ISSUE TITLE
Getting this error 

### ISSUE THREAD

**Issue by katywilliams1121** [gcui-art/suno-api#46]
![Screenshot_2024-04-22-15-56-04-206_com android chrome](https://github.com/gcui-art/suno-api/assets/151863894/5a98a3f2-0a3a-41f3-96a5-05fa9f90462b)

how to resolve this

i followed every steps

**Comment by blueeon** [comment]
@katywilliams1121 If this is a bug, could you submit a PR to fix it? The community would really appreciate it. ❤️
