### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by yuanjie-ai** [gcui-art/suno-api#47]
{"error":"Internal server error. Error: Failed to get session id, you may need to update the SUNO_COOKIE"}%                                                                                                                             
<img width="548" alt="image" src="https://github.com/gcui-art/suno-api/assets/20265321/e530b847-7bc9-4a5e-a7f8-1ec32e35a658">

**Comment by blueeon** [comment]
Provide more context and resubmit the issue following the template.
