### ISSUE TITLE
为什么我会卡在这里啊

### ISSUE THREAD

**Issue by YuanYuanrow** [gcui-art/suno-api#68]
真的很抱歉打扰您，但是我的部署到本地时会卡在ready这里之后就没有反映了
![屏幕截图 2024-05-08 115215](https://github.com/gcui-art/suno-api/assets/128216209/630b5915-2dfe-4402-8e9d-732604a225b3)

**Comment by YuanYuanrow** [comment]
会不会和配置有关系，我第一次cookies没改就运行了，这个是一次重新开始的配置，但是旧的操作没删过

**Comment by blueeon** [comment]
This is standard procedure; if the service isn’t functioning correctly, you might need to set up a .env file and adjust the cookie configuration.

**Comment by YuanYuanrow** [comment]
thank you it is solved!
