### ISSUE TITLE
/extend_audio endpoint is returning 500s, Internal Error 'Unauthorized'

### ISSUE THREAD

**Issue by snakewizardd** [gcui-art/suno-api#71]
/extend_audio endpoint is returning 500s, Internal Error 'Unauthorized'

All the other endpoints work. I'm consistently running up against these 500s though. I tried with the swagger docs as well as pinging from my own script - I am supplying the body correctly

Is this endpoint /extend_audio functional?

**Comment by monsinghcharles** [comment]
Im facing the same issue

**Comment by Alex-Golod** [comment]
Me also.

**Comment by blueeon** [comment]
I resolved it after updating the cookie.

**Comment by isabellapu** [comment]
hi, I am still facing this issue. I don't think it's a cookie issue as I just checked that my cookie is correct?

**Comment by marriog2** [comment]
me too, cookie is good but same 500 issue.
