### ISSUE TITLE
Random Style request.

### ISSUE THREAD

**Issue by Grote5que7** [gcui-art/suno-api#72]
Thank you for your hard work!

Suno have the option to generate Random Style for music (in custom mode under Style of Music). Can we have the option in API too? I would like to use it.

**Comment by blueeon** [comment]
In fact, it is just randomly selected from a limited list. If you need, you can easily find a list of music genres on the Internet, such as: https://en.wikipedia.org/wiki/List_of_music_genres_and_styles
