### ISSUE TITLE
How to get whole song (including all extend parts)? 

### ISSUE THREAD

**Issue by rustem-git** [gcui-art/suno-api#78]

**Comment by alifhughes** [comment]
I've created a PR for this functionality: https://github.com/gcui-art/suno-api/pull/79

**Comment by rustem-git** [comment]
Amazing job! Thank you very much!

If we don't have a live example of this functionality, I think it's necessary to add information to the description about passing the ID of the last part (if I understood correctly) and provide an example of what it should look like. For instance,

src/app/docs/page.tsx

/api/concat?clid_id=XXX: Generate the whole song from extensions. Get the ID of the last extend. Returns data for the full version of the song.

Correct me if I misunderstood or wrote something incorrectly. It is only example.

---
Question: In the last two days, I have been getting a 500 error.
"Internal server error. Error: Failed to get session id, you may need to update the SUNO_COOKIE."
I checked your demo version. It shows the same error. 
During this time, I have changed the information about suno_cookie several times, but it doesn't give any results. Nothing works. I tried different account and nothing. Maybe you know what to do with it?

**Comment by blueeon** [comment]
Thank you  your hard work ❤️ @alifhughes

**Comment by alifhughes** [comment]
No worries!
