### ISSUE TITLE
类型为“string |null' 不能分配给 'string' 类型的参数

### ISSUE THREAD

**Issue by 1152588263** [gcui-art/suno-api#83]
编译失败。
19:16:59.561 |  
19:16:59.562 | ./src/app/api/clip/route.ts：12：55
19:16:59.562 | 类型错误：类型为“string \|null' 不能分配给 'string' 类型的参数。
19:16:59.563 | 类型“null”不能分配给类型“string”。
19:16:59.563 |  
19:16:59.563 | 10 \| const url = new URL（req.网址）;
19:16:59.563 | 11 \| const clipId = url。searchParams。get（'id');
19:16:59.564 | > 12 \| const audioInfo = await （await sunoApi）。getClip（剪辑 Id）;
19:16:59.564 | \|                                                       ^
19:16:59.564 | 13 \|
19:16:59.565 | 14 \| 返回 new NextResponse（JSON.stringify（audioInfo）， {
19:16:59.565 | 15 \| 状态： 200，
19:16:59.617 | ELIFECYCLE 命令失败，退出代码为 1。
19:16:59.637 | 错误：命令“pnpm run build”退出，并显示 1
19:17:00.043

**Comment by blueeon** [comment]
Pull the latest code and verify if this issue has been resolved.
