### ISSUE TITLE
Version 3.5: .wav URL / download?

### ISSUE THREAD

**Issue by RaouleMenard** [gcui-art/suno-api#88]
So version 3.5 is now out. One new feature is the possibility to download a .wav version.

The current GET function doesn't provide a .wav URL for download.

Can you please update it?

Thanks.

**Comment by hzlzh** [comment]
+1

**Comment by partiesforum** [comment]
Just change the .mp3 to WAV. The main URL path stays the same.

**Comment by lolifamily** [comment]
+1

**Comment by blueeon** [comment]
#101

**Comment by blueeon** [comment]
@RaouleMenard You’re correct, there’s a new GEN API available.
