### ISSUE TITLE
Update to 3.5

### ISSUE THREAD

**Issue by Tasteslikeawesome** [gcui-art/suno-api#91]
All projects are still generating in 3.0 model.
Add option to switch between v3 & v3.5(Early Access)

**Comment by blueeon** [comment]
Okay, I may have a brief vacation next week, I will make time to deal with it.
The new product has taken up all my time recently, I need to find a gap, although slowly, I will continue to maintain it.

**Comment by jochemstoel** [comment]
Hey guys, @Tasteslikeawesome 

To use v3.5,  simply open _SunoApi.ts_ in your _/src/lib_  folder, and on line 166 change this:
```js
mv: "chirp-v3-0",
```
into this:
```
mv: "chirp-v3-5",
```

**Comment by blueeon** [comment]
Upgrade by  @LordSkare  #93 
Let’s give him a big round of applause!

**Comment by jochemstoel** [comment]
> Upgrade by @LordSkare #93 Let’s give him a big round of applause!

Puh, I deserve that applause.

**Comment by blueeon** [comment]
I’ve made some enhancements by including the model number as an optional parameter.
#101
